### PR TITLE
Add an in place topological sorting algorithm

### PR DESCRIPTION
**Pull request by hchokshi**
There is an issue with the topological sorting implementation added in #13 - since it uses Kahn's algorithm, it must operate on a copy of the graph or modify the original graph. The graph cloning can be quite an intensive process for larger graphs - it can require a large amount of memory (e.g. custom `Node` implementations that have large arbitrary data) and could also be time intensive if there are a lot of vertices / edges.

The implementation attached in this pull request uses a depth first search based approach which can be applied without copying the graph. It achieves the same O(V+E) time as Kahn's algorithm, but can be done with a predictable amount of memory. The only additional memory it allocates is an integer array in O(V) - the Kahn's algorithm approach requires to allocate space for `Node` objects in O(V).

My implementation is fully compatible with the existing Kahn's algorithm version, and just requires using an instance of `InPlaceTopologicalSort` instead of `TopologicalSort` - it can even be passed where an instance of `TopologicalSort` is expected.

### CODE REVIEW

**Comment by jordilaforge** [comment]
@hchokshi nice coding for jure dfs is the better approach because copying is not needed but somebody has to start somewhere isn't it ;-)
Thanks for your efforts

**Comment by hchokshi** [comment]
@jordilaforge 
How is this? I moved the DFS sort into the same class, added an argument constructor to choose algorithm. No arg constructor defaults to DFS so any existing code will automatically switch to DFS.

I've also made a bunch of changes that I believe improve readability / maintainability (e.g. replacing the copy method for Kahn's algorithm with a call to the existing `Graphs.clone()`) and making all exceptions be instances of `GraphHasCycleException` (which extends `IllegalStateException` for backwards compatibility).

---

Additionally, I'm not sure that having Kahn's algorithm is necessary in the first place. While the two algorithms may provide different permutations of topological sort, the solutions should be interchangeable and having a choice may confuse users. The DFS algorithm seems to be the better choice in all cases, due to predictable memory usage and no copy step adding to the runtime.

It may be better to just have this class offer DFS sort, to avoid requiring ongoing maintenance of the Kahn's algorithm implementation due to people using it in their code.

**Comment by jordilaforge** [comment]
Totally agree with your changes on Graphs.clone and with the exception handeling it was my first PR on graphstream therefore i didn't know much of graphstream yet. I see your point about removing kahn totally i just wanted to keep it for sake of completion..

**Comment by hchokshi** [comment]
@jordilaforge It's good that you made the pull request in the first place, and added a necessary feature to a library you are using! :)

**Comment by jordilaforge** [comment]
@hchokshi I will keep them PR coming :-) next up is longest path in a DAG but im kind of stuck and I don't find much time for it. BTW I changed my original answer on removing kahn, in the end i want to implement I proper hierarchical layout by using graham or longest path for layering. Therefore kahn is needed.

**Comment by jordilaforge** [comment]
Can somebody merge this please?

**Pull request merged**
