### PR TITLE
Feature/longest-path-dag

### PR DESCRIPTION
**Pull request by jordilaforge**

### CODE REVIEW

**Comment by jordilaforge** [comment]
This is a new pull request out of the old longest path pull request. This features a weight attribute and a helper method to get the longest path as a Graphstream Path type.

**Comment by hichbra** [comment]
You need to use the 2.x branch in gs-core and change the build path for java 1.8.

**Comment by jordilaforge** [comment]
@hichbra ok then I will provide a new PR for the branch 2.x with streams

**Comment by hichbra** [comment]
Provide a new pull request is not necessary, you can change the base branch of this PR.

**Comment by jordilaforge** [comment]
@hichbra thanks I know but this feature will then just be in the 2.x branch not in the master

**Comment by hichbra** [comment]
Ok then I'll recap : 
- Remove graph cloning :+1: 
- Provide "weightAttribute"  :+1: 
- Return a graph.Path :+1: 

Everything it's ok then I merge this PR. We are waiting your version in the 2. x branch.

**Pull request merged**
